using UnityEngine;
using System.Collections;
/*Define todas las constantes utilizas en la aplicacion*/
public class AppIUConstantes{
	public static string CADENA_VACIA="";
	public static string PUNTO=".";	
	public static string BOTON_ACEPTAR="Aceptar";
	public static string BOTON_CANCELAR="Volver";
	public static string BOTON_ENVIAR="Enviar";
	public static string MENSAJE_ERROR="INGRESE VALORES NUMERICOS: ";	
	public static string TITULO_SERVIDOR="ERROR AL CONECTAR AL SERVIDOR!";
	public static string TITULO_DIARIO="Diarios Digitales";	
	public static string MENSAJE_AYUDA1="   1. -Revise la conexión a la red wifi";
	public static string MENSAJE_AYUDA2="   2. -Revise la dirección del servidor:";
	public static string STRING_PLATOS="PLATOS";
	public static string STRING_BEBIDAS="BEBIDAS";
	public static string ESTADO_REALIZADO="REALIZADO";
	public static string ESTADO_PENDIENTE="PENDIENTE";
	public static string STRING_DESCRIPCION="DESCRIPCION";
	public static string STRING_PRECIO="PRECIO";
	public static string STRING_CANTIDAD="CANTIDAD";
	public static string STRING_ESTADO="ESTADO";
	public static string STRING_TOTAL="TOTAL";
	public static string DESCRIPCION_MESA1="ADELANTE A LA DERECHA";
	public static string DESCRIPCION_MESA2="ADELANTE A LA IZQUIERDA";
	public static string DESCRIPCION_MESA3="ATRAS A LA IZQUIERDA";
	public static string DESCRIPCION_MESA4="ATRAS A LA DERECHA";
	public static string FLECHA="->";
	public static string FORMATO_FECHA="MM/dd/yyyy";
	public static string HTTP="http://";
	public static string PHP_SELECT_MENU="/registroSalvado/selectMenu.php";
	public static string PHP_GUARDAR_PEDIDO="/registroSalvado/guardar_pedido.php?";
	public static string PHP_INDICE_MAYOR="/registroSalvado/indice_mayor_pedido.php";
	public static string PHP_GUARDAR_TEA="/registroSalvado/guardar_tea_menu_pedido.php?";
	public static string PHP_SELECT_DIARIO="/registroSalvado/select_diario.php";
	public static string PHP_SELECT_VIDEO="/registroSalvado/select_video_activo.php";
	public static string PHP_SELECT_MESA="/registroSalvado/select_mesa.php";
	public static string TITULOS_AUTORES="ALUMNOS";	
	public static string AUTOR1="Vale, Walter Jesús";
	public static string AUTOR2="Carrizo, Fernando Martín";
	public static string TITULOS_TUTOR="TUTOR";
	public static string TUTOR="Reinoso, Elizabeth";
	public static string DERECHOS_AUTOR="Esta aplicación es propiedad de sus autores y de la Facultad de Ingeniería de Jujuy.";
	public static string MESA_TITULO="SELECCIONE LA MESA";
	public static string MESA_LABEL="Nº Mesa:";
	public static string MESA_SELECCION="Elija";
	public static string MESA_ELECCION_MESA="?";
	public static string MESAJE_ERROR_COMBOBOX="Elija una opción!";
	public static int MAX_LENGTH=3;
	public static int MAX_MATRIZ=5;
	public static int MAX_MENU=4;
	public static int MAX_CATEGORIA=2;
	public static int MAX_PLATOS=10;
    public static int[] NUMEROMESA={1,2,3,4};
	public static float TIEMPO_ESPERA1=0.5f;
	public static float TIEMPO_ESPERA2=2f;
	public static float TIEMPO_ESPERA3=1f;
}
